CREATE TABLE Products(
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	Name VARCHAR(255),
	MSRP FLOAT,
	Description VARCHAR(255),
	CreationDate DATETIME NOT NULL,
	CUP VARCHAR(255),
	CategoryID VARCHAR(255)
);