CREATE TABLE Items(
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	ProductID VARCHAR(255) FOREIGN KEY REFERENCES Products(ID),
	Cost FLOAT,
	SerialNumber VARCHAR(255),
	CreationDate DATETIME,
	ReceptionDate DATETIME
);