CREATE TABLE Users (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	UserName VARCHAR(20),
	Password VARCHAR(20),
	Email VARCHAR(255),
	CreationDate DATETIME NOT NULL,
	CartID VARCHAR(255),
	Address VARCHAR(255)
)