//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGEGWebClient.SGEGService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGEGService.ISGEGPublicService")]
    public interface ISGEGPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGEGPublicService/GetPublicMessage", ReplyAction="http://tempuri.org/ISGEGPublicService/GetPublicMessageResponse")]
        string GetPublicMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISGEGPublicServiceChannel : SGEGWebClient.SGEGService.ISGEGPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SGEGPublicServiceClient : System.ServiceModel.ClientBase<SGEGWebClient.SGEGService.ISGEGPublicService>, SGEGWebClient.SGEGService.ISGEGPublicService {
        
        public SGEGPublicServiceClient() {
        }
        
        public SGEGPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SGEGPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGEGPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGEGPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPublicMessage() {
            return base.Channel.GetPublicMessage();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGEGService.ISGEGPrivateService")]
    public interface ISGEGPrivateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISGEGPrivateService/GetPrivateMessage", ReplyAction="http://tempuri.org/ISGEGPrivateService/GetPrivateMessageResponse")]
        string GetPrivateMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISGEGPrivateServiceChannel : SGEGWebClient.SGEGService.ISGEGPrivateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SGEGPrivateServiceClient : System.ServiceModel.ClientBase<SGEGWebClient.SGEGService.ISGEGPrivateService>, SGEGWebClient.SGEGService.ISGEGPrivateService {
        
        public SGEGPrivateServiceClient() {
        }
        
        public SGEGPrivateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SGEGPrivateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGEGPrivateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SGEGPrivateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPrivateMessage() {
            return base.Channel.GetPrivateMessage();
        }
    }
}
